spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/livrin
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: localhost
    port: 1025
    username: hatem
    password: hatem
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimeout: 6000
        timeout: 3000
        writetimeout: 6000

application:
  security:
    jwt:
      secret-key: 52620cf18454ad7c742a729109c4c4c17881a2fb7b6f4669daa7e0d010f78bc4
      expiration: 8640000
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account

server:
  port: 8088
